### PR TITLE
included the perseus_dictionary dataset

### PR DESCRIPTION
**Pull request by daranzolin**
Included `perseus_dictionary` as a dataset. See `data/perseus_catalog.R` for details.

### CODE REVIEW

**Comment by lmullen** [comment]
Thanks for the pull request. This package is used primarily for teaching. The idea is that each dataset should be able to be used for some purpose. E.g., dataset x makes map y. I'm having a little difficulty figuring out what this dataset could be used to illustrate for teaching purposes. Could you please give me a few examples of how someone might use this dataset in the classroom?

**Comment by daranzolin** [comment]
Thanks Lincoln. I think there are several teaching opportunities here. The `entry` column is semi-organized text and could be used to introduce regular expressions while scanning the entries for "Greek Sophists", "Roman Senators", "Christian Martyrs", or "Olympians." If for example, you were researching historical figures associated with "Gaul", you could grep them here. Or you could search for all mythological figures associated with "Athena" or "Artemis". I could whip up an RPubs script if you'd like.

**Comment by daranzolin** [comment]
Played around with the dataset here: http://rpubs.com/daranzolin/perseus_dictionary. There are also ample `tidytext` opportunities.

**Comment by lmullen** [comment]
@daranzolin Thanks for the PR. I see you have a Perseus-related package under review at rOpenSci. It would be better to keep all the Perseus related things in that package, so I'm not going to merge this request.

**Pull request closed without merging**
