### PR TITLE
Add `R-CMD-check` workflow

### PR DESCRIPTION
**Pull request by jrdnbradford**
I found this repo through the rOpenSci newletter and see there's an issue (#23) for maintaining and volunteering. I wouldn't mind doing a few things to spruce this up a bit, @maelle. 

For starters, this adds a basic `R-CMD-check` workflow that should make it easier to integrate and test changes.

### CODE REVIEW

**Comment by maelle** [comment]
Thank you! Do you want to keep adding me as a reviewer (fine with me) or would you like to get write access?

**Comment by maelle** [comment]
(I was on vacation, usually it shouldn't take me _weeks_ to respond :slightly_smiling_face:)

**Comment by jrdnbradford** [comment]
@maelle no worries! I think write access would be great. Thank you!

**Comment by maelle** [comment]
If you decide to become the maintainer, please ping me again so I might increase your access once again :wink:

**Comment by jrdnbradford** [comment]
@maelle thanks for the access. I resolved several issues and made quite a few updates that included bug fixes, new datasets, package infrastructure updates, and docs, resulting in the release of [v0.3.0](https://github.com/ropensci/historydata/releases/tag/v0.3.0). 

I don't think I'm the right person to be the maintainer of this particular repo, but I hope my changes will lower the barrier to someone else accepting that role.

You can remove my write access if you'd like.

Thanks! 🤖

**Comment by maelle** [comment]
Thank you!!

**Comment by maelle** [comment]
@jrdnbradford even if you don't want to become the maintainer, you'd be welcome to join our slack workspace. If that's interesting to you, please share your email address with me here or at `maelle@ropensci.org`. Thanks!

**Pull request merged**
